// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeL2HQOtAhhgdFvYuXNfrJPcfyEbGl704',
    appId: '1:627831708505:web:da451d068da859e2fbca48',
    messagingSenderId: '627831708505',
    projectId: 'soz-lugat',
    authDomain: 'soz-lugat.firebaseapp.com',
    storageBucket: 'soz-lugat.firebasestorage.app',
    measurementId: 'G-B7GRBY221W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXHjYAKul9raPEhrGZuvxW-bKHh60adgk',
    appId: '1:627831708505:android:68634a6abc3cd1dffbca48',
    messagingSenderId: '627831708505',
    projectId: 'soz-lugat',
    storageBucket: 'soz-lugat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc749n6d885xBRCPoDlIrXUrRQCkq3bLY',
    appId: '1:627831708505:ios:7600f97fe1bba81bfbca48',
    messagingSenderId: '627831708505',
    projectId: 'soz-lugat',
    storageBucket: 'soz-lugat.firebasestorage.app',
    iosBundleId: 'com.enigma.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc749n6d885xBRCPoDlIrXUrRQCkq3bLY',
    appId: '1:627831708505:ios:c2d26d60261649c6fbca48',
    messagingSenderId: '627831708505',
    projectId: 'soz-lugat',
    storageBucket: 'soz-lugat.firebasestorage.app',
    iosBundleId: 'com.example.soz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeL2HQOtAhhgdFvYuXNfrJPcfyEbGl704',
    appId: '1:627831708505:web:cb110164cb9a8868fbca48',
    messagingSenderId: '627831708505',
    projectId: 'soz-lugat',
    authDomain: 'soz-lugat.firebaseapp.com',
    storageBucket: 'soz-lugat.firebasestorage.app',
    measurementId: 'G-36EP22LF1K',
  );

}